dist: trusty
sudo: required
language: node_js
node_js:
- "8"
os:
- linux
install:
- npm install
script:
- npm run report:coverage
- npm run release
deploy:
- provider: script
  script: npm run release
  on:
    branch: master
- provider: npm
  email: kevin.kreuzer90@icloud.com
  api_key: ${NPM_KEY}
  script: npm run release
  on:
    tags: true
  skip_cleanup: true
